### ISSUE TITLE
Missing git tags for latest versions

### ISSUE THREAD

**Issue by untitaker** [dmfs/tasks#126]
For some reason FDroid is still on 1.0, not necessarily because of this, but still.

**Comment by dmfs** [comment]
Not sure what exactly you mean. All our releases are tagged, see https://github.com/dmfs/tasks/tags
However, I just noticed that I didn't push the latest tags yet. I'll do that next week. Also, we've published the binaries of every public release under https://github.com/dmfs/tasks/tree/master/releases

**Comment by untitaker** [comment]
Sorry for the confusion, I did mean that you forgot to use tags for the latest few releases. I think F-Droid goes by tags when watching for new versions, which is why this is important to me.

**Comment by untitaker** [comment]
@dmfs any updates on this?

Since 1.1.1 there are no new tags although from the commit log it seems you're already on 1.1.6.

**Comment by dmfs** [comment]
sorry, all tags are pushed to github now.
